### ISSUE TITLE
Distribute yuniql as GitHub Action in GitHub Market Place

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#158]
It could be a good idea to explore making `yuniql` available in GH Action Market Place. Possible actions are:
-
-

```yaml
name: yuniql
on:
  push:
    branches:
      - master
jobs:
  up:
    name: yuniql run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yuniql/actions@v1
        with:
          command: run
        env:
          YUNIQL_TARGET_PLATFORM: sqlserver
          YUNIQL_CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
```       

https://github.community/t/how-to-publish-a-github-action-in-the-marketplace/16411
https://github.com/actions/typescript-action
