### ISSUE TITLE
Gitlab pipeline failed with exit code 1 when i try to get version

### ISSUE THREAD

**Issue by Konversys** [rdagumampan/yuniql#291]
I have got a gitlab-ci.yaml  

```
deploy:
  state: deploy
  script:
  - echo "deploy"
  - yuniql version
```

The result of this job is:
```
$ yuniql version
yuniql 1.3.15
ERROR: Job failed: exit status 1
```
