### ISSUE TITLE
Automation: Create az pipelines for deploying az task into marketplace

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#31]
Automation: Create az pipelines for deploying az task into marketplace

An azure pipeline task has been on preview in Az DevOps Market Place. Updating the package is becoming tedious as I have to:

1. Update the Install Task
2. Update the Run Task
3. Update the `vss-extension.json` file
3. Run `tsc`
4. Run `tfx cli`
5. Upload to marketplace

Reference:
https://marketplace.visualstudio.com/items?itemName=rdagumampan.yuniql-azdevops-extensions

**Comment by rdagumampan** [comment]
Build pipeline

```yaml
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pr:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@0
  displayName: 'install typescript'
  inputs:
    arguments: 'typescript@2.8.1 --global-style'

- task: Npm@0
  displayName: 'install tfx-cli command'
  inputs:
    arguments: 'tfx-cli@v0.7.6 --global'

- task: CmdLine@2
  inputs:
    workingDirectory: $(Build.SourcesDirectory)/src
    script: |
      npm install

- task: CmdLine@2
  inputs:
    workingDirectory: $(Build.SourcesDirectory)/src
    script: |
      tsc

- task: CmdLine@2
  inputs:
    workingDirectory: $(Build.SourcesDirectory)
    script: |
      tfx extension create --manifest-globs vss-extension.json

- task: CmdLine@2
  inputs:
    workingDirectory: $(Build.SourcesDirectory)
    script: |
      tfx extension create --manifest-globs vss-extension.json

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
```

Release pipeline
```yaml
steps:
- task: NodeTool@0
  displayName: 'Use Node 6.x'

steps:
- task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishAzureDevOpsExtension@2
  displayName: 'Publish Extension'
  inputs:
    connectedServiceName: 'az-marketplace'
    fileType: vsix
    vsixFile: '$(System.DefaultWorkingDirectory)/_rdagumampan.yuniql-azure-pipelines-tasks/drop/*.vsix'
    extensionVersion: '0.$(Release.ReleaseId).0'
    extensionVisibility: public
    extensionPricing: free
    bypassLocalValidation: true
    noWaitValidation: true
```
