### ISSUE TITLE
French characters are turned to unreadable characters when deploying using Azure DevOps Pipelines

### ISSUE THREAD

**Issue by ayadiwork** [rdagumampan/yuniql#314]
Hello,
I have some french characters in my script : 'é', 'è', 'â' ....
But those characters are turned to non readable characters.
![image](https://github.com/rdagumampan/yuniql/assets/28810269/312dca3e-e026-4279-bf3e-dc2bd74fc799)
I am using Postgresql on Azure Also.
Here my ADO task : 

   
```
  - task: rdagumampan.yuniql-azdevops-extensions.run-task.RunYuniqlCLI@1
            displayName: 'Run Yuniql'
            inputs:
                connectionString: 'MyServiceConnectionName'
                workspacePath: '$(System.DefaultWorkingDirectory)/Yuniqlfolder'
                targetPlatform: postgresql
                autoCreateDatabase: true
                additionalArguments: '--debug'
```
