### ISSUE TITLE
Support Linux Az DevOps agents

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#53]

**Comment by rdagumampan** [comment]
Done. The next release of yuniql az pipeline tasks supports Linux build agents. The extensions has been tested to work with Ubuntu-based agents. 

```yaml
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CmdLine@2
  displayName: clone postgresql samples repo
  inputs:
    script: |
      git clone https://github.com/rdagumampan/yuniql $(Build.SourcesDirectory)/yuniql

- task: UseYUNIQLCLI@1
  displayName: yuniql install
  inputs:
    version: 'latest'

- task: EraseYuniqlCLI@1
  displayName: yuniql erase
  inputs:
    version: 'latest'
    connectionString: '$(AwsPostgreSqlDemoDatabase)'
    workspacePath: '$(Build.SourcesDirectory)/yuniql/samples/basic-postgresql-sample'
    targetPlatform: 'postgresql'
    additionalArguments: '--debug'

- task: RunYUNIQLCLI@1
  displayName: yuniql run
  inputs:
    version: 'latest'
    connectionString: '$(AwsPostgreSqlDemoDatabase)'
    workspacePath: '$(Build.SourcesDirectory)/yuniql/samples/basic-postgresql-sample'
    targetPlatform: 'PostgreSql'
    additionalArguments: '--debug'

- task: VerifyYuniqlCLI@1
  displayName: yuniql verify
  inputs:
    version: 'latest'
    connectionString: '$(AwsPostgreSqlDemoDatabase)'
    workspacePath: '$(Build.SourcesDirectory)/yuniql/samples/basic-postgresql-sample'
    targetPlatform: 'PostgreSql'
    additionalArguments: '--debug'
```

![image](https://user-images.githubusercontent.com/5895952/85926494-2dbf2080-b8a0-11ea-8ff1-e464e915f4cc.png)
