### ISSUE TITLE
Add test run to docker containers win and linux

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#56]
When docker base images are built in AppVeyor, we execute a test migration run to ensure images for both Windows and Linux executes migration successfully.

**Comment by rdagumampan** [comment]
Done. 

The goal is to make sure the latest image built is verified to work and run an actual migration.

Created test azure pipelines to test docker-based migrations based on latest docker image. The test run is created only for PostgreSql using Amazon RDS - PostgreSql Free Tier. It assumed, it would work for all supported databases.

## Task: Build docker image

```yaml
steps:
- task: Docker@2
  displayName: 'Build docker image'
  inputs:
    command: build
    Dockerfile: '$(System.DefaultWorkingDirectory)/_rdagumampan_yuniql/samples/basic-postgresql-sample/Dockerfile'
    arguments: '-t postgresql-sample'
    addPipelineData: false
```

## Task: Run docker image

```yaml
#Your build pipeline references a secret variable named ‘AwsPostgreSqlDemoDatabase’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: Docker@2
  displayName: 'Run docker image'
  inputs:
    command: run
    arguments: 'postgresql-sample --platform postgresql -c "$(AwsPostgreSqlDemoDatabase)" --debug'
    addPipelineData: false
```
